# Generated by Django 4.1.13 on 2024-06-18 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testimonials",
            old_name="Image",
            new_name="image",
        ),
        migrations.AddField(
            model_name="testimonials",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
