# Generated by Django 4.1.13 on 2024-06-18 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_skills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
