# Generated by Django 4.1.13 on 2024-06-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_skills_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_service",
            name="boostrap_logo",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="my_service",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
