# Generated by Django 4.1.13 on 2024-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_my_service_boostrap_logo_alter_my_service_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messages",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="messages",
            old_name="Message",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="messages",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="messages",
            old_name="Subject",
            new_name="subject",
        ),
        migrations.RemoveField(
            model_name="my_works",
            name="logo",
        ),
        migrations.AddField(
            model_name="my_works",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Portfolio/"),
        ),
        migrations.AddField(
            model_name="my_works",
            name="video",
            field=models.URLField(blank=True),
        ),
    ]
