# Generated by Django 4.1.13 on 2024-06-18 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_rename_email_messages_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="my_works",
            old_name="fields",
            new_name="field",
        ),
    ]
